name: intertwined
description: A Text Snippets utility

publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  string_validator: ^0.1.4
  provider: ^4.3.2+2
  github_sign_in: ^0.0.1
  flutter_svg: ^0.19.0
  cached_network_image: ^2.3.3
  responsive_builder: ^0.3.0
  
  # firebase
  firebase_core: ^0.5.0+1
  cloud_firestore: ^0.14.1+3
  firebase_auth: ^0.18.1+2
  google_sign_in: ^4.5.4

  # fonts
  google_fonts: any


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/illustrations/
    - assets/illustrations/png/

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "icons/intertwined.png"
  adaptive_icon_background: "#161925"
  adaptive_icon_foreground: "icons/intertwined-nobg.png"