name: intertwined
description: Work Faster. Work Better.

publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  string_validator: ^0.3.0
  provider: ^5.0.0
  github_sign_in: ^0.0.4
  flutter_svg: ^0.21.0+1
  cached_network_image: ^3.0.0
  responsive_builder: ^0.4.1
  url_launcher: ^6.0.3
  
  # firebase
  firebase_core: ^1.0.3
  cloud_firestore: ^1.0.4
  firebase_auth: ^1.0.3
  google_sign_in: ^5.0.1

  # fonts
  google_fonts: any


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/illustrations/
    - assets/illustrations/png/

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "icons/intertwined.png"
  adaptive_icon_background: "#161925"
  adaptive_icon_foreground: "icons/intertwined-nobg.png"